"""implement memory inheritance

Revision ID: 0dd98ca7a0ae
Revises: 0002
Create Date: 2026-07-20 12:46:15.684290
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0dd98ca7a0ae"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("memory_type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=255), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("embedding_reference", sa.String(length=255), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("previous_version_id", sa.String(length=36), nullable=True),
        sa.Column("superseded_by_id", sa.String(length=36), nullable=True),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["previous_version_id"],
            ["memories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_id"],
            ["memories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("memories", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_memories_project_id"), ["project_id"], unique=False)

    op.create_table(
        "memory_bugs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("problem", sa.Text(), nullable=False),
        sa.Column("root_cause", sa.Text(), nullable=True),
        sa.Column("solution", sa.Text(), nullable=True),
        sa.Column("affected_files", sa.JSON(), nullable=True),
        sa.Column("severity", sa.String(length=50), nullable=True),
        sa.Column("resolved", sa.Boolean(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["memories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "memory_decision_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("decisions_referenced", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["memories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "memory_decisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("decision", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("alternatives", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["memories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "memory_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("event_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["memories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "memory_features",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("acceptance_criteria", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["memories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "memory_notes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["memories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("architecture_decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_architecture_decisions_project_id"))

    op.drop_table("architecture_decisions")
    with op.batch_alter_table("bugs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bugs_project_id"))

    op.drop_table("bugs")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bugs",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("project_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("title", sa.VARCHAR(length=255), nullable=False),
        sa.Column("problem", sa.TEXT(), nullable=False),
        sa.Column("root_cause", sa.TEXT(), server_default=sa.text("('')"), nullable=True),
        sa.Column("solution", sa.TEXT(), server_default=sa.text("('')"), nullable=True),
        sa.Column("affected_files", sqlite.JSON(), nullable=True),
        sa.Column(
            "severity", sa.VARCHAR(length=50), server_default=sa.text("'medium'"), nullable=True
        ),
        sa.Column("resolved", sa.BOOLEAN(), server_default=sa.text("1"), nullable=True),
        sa.Column("resolved_at", sa.DATETIME(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bugs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bugs_project_id"), ["project_id"], unique=False)

    op.create_table(
        "architecture_decisions",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("project_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("title", sa.VARCHAR(length=255), nullable=False),
        sa.Column("decision", sa.TEXT(), nullable=False),
        sa.Column("reason", sa.TEXT(), server_default=sa.text("('')"), nullable=True),
        sa.Column("alternatives", sqlite.JSON(), nullable=True),
        sa.Column(
            "status", sa.VARCHAR(length=50), server_default=sa.text("'accepted'"), nullable=True
        ),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("architecture_decisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_architecture_decisions_project_id"), ["project_id"], unique=False
        )

    op.drop_table("memory_notes")
    op.drop_table("memory_features")
    op.drop_table("memory_events")
    op.drop_table("memory_decisions")
    op.drop_table("memory_decision_logs")
    op.drop_table("memory_bugs")
    with op.batch_alter_table("memories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memories_project_id"))

    op.drop_table("memories")
    # ### end Alembic commands ###
