"""add metadata to conversations

Revision ID: 34fd9197f989
Revises: ecf5f724818b
Create Date: 2026-08-03 15:43:20.788347
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34fd9197f989"
down_revision: str | None = "ecf5f724818b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("metadata_", sa.String(), server_default="{}", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_column("metadata_")
    # ### end Alembic commands ###
