"""Add Conversation domain models

Revision ID: ecf5f724818b
Revises: 0dd98ca7a0ae
Create Date: 2026-07-20 14:12:19.872720
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ecf5f724818b"
down_revision: str | None = "0dd98ca7a0ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversation_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversation_sessions_conversation_id"),
            ["conversation_id"],
            unique=False,
        )

    op.create_table(
        "conversation_summaries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), server_default="0", nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversation_summaries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversation_summaries_conversation_id"),
            ["conversation_id"],
            unique=False,
        )

    op.create_table(
        "conversation_citations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("message_id", sa.String(length=36), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("source_reference", sa.String(length=255), nullable=False),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversation_citations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversation_citations_message_id"), ["message_id"], unique=False
        )

    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("state", sa.String(length=50), server_default="ACTIVE", nullable=False)
        )
        batch_op.drop_column("summary")
        batch_op.drop_column("message_count")
        batch_op.drop_column("summary_token_count")

    # (Skipping invalid drop_constraint on messages table)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")  # type: ignore
        batch_op.create_foreign_key(None, "conversations", ["conversation_id"], ["id"])

    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "summary_token_count", sa.INTEGER(), server_default=sa.text("'0'"), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column("message_count", sa.INTEGER(), server_default=sa.text("'0'"), nullable=True)
        )
        batch_op.add_column(
            sa.Column("summary", sa.TEXT(), server_default=sa.text("('')"), nullable=True)
        )
        batch_op.drop_column("state")

    with op.batch_alter_table("conversation_citations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversation_citations_message_id"))

    op.drop_table("conversation_citations")
    with op.batch_alter_table("conversation_summaries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversation_summaries_conversation_id"))

    op.drop_table("conversation_summaries")
    with op.batch_alter_table("conversation_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversation_sessions_conversation_id"))

    op.drop_table("conversation_sessions")
    # ### end Alembic commands ###
